### ISSUE TITLE
Is there a way to use custom FEEL functions?

### ISSUE THREAD

**Issue by antback** [DecisionToolkit/dsntk#25]
Hi!!

Very interesting project! Thanks for sharing.

I would like to know if I can define my own FEEL functions. For example, I would like to compare strings using fuzzy. 

Thanks!

**Comment by ghost** [comment]
[DMN specification](https://www.omg.org/spec/DMN/1.5/Beta1/PDF) defines how to use externally-defined functions:

![image](https://github.com/dsntk/dsntk-rs/assets/149608688/b00b066e-9184-41ba-9854-64b3ac91f3f0)

"Officially", this is the only way to add custom functions to the model, but I have already seen, that other vendors support multiple functions not defined by the DMN standard, and there is an open discussion in the standarization group, how to make it easier. Current state is, that external functions must be written in Java (the whole specification is unfortunately not Rust-friendly).

Anyway, I was thinking multiple times (knowing the user needs) about introducing some kind of extensionability  to DSNTK (although it's against DMN specification).

But getting to the point:
- If you know exactly what your function should do, and you are able to write it in Java, then please prepare such function and I will provide you an example of the model that uses this function in DSNTK. Following this example you can add your own functions in the future the same way.
- If the performance is an issue, then calling external function written in Java is not the best option. In such case we can implement such function directly in DSNTK in Rust and expose it to be used in any model (but such model will not be conformant with the DMN specification and will not be portable to other DMN runtimes).

I hope I could shed some light on this topic. Let me know which way we can help further.

Thanks for trying **DSNTK**!

**Comment by ghost** [comment]
Hi @antback,

I am closing this issue but feel free to reopen or comment on it when needed.

Regards.
