### ISSUE TITLE
Support for napi.rs

### ISSUE THREAD

**Issue by ghost** [DecisionToolkit/dsntk#5]
Hi @magick93,

I have recreated your issue according [napi.rs](https://crates.io/crates/napi) support.

Could you provide an example of a use-case for such support? Do I understand it correctly, that you would like to embed a DMN runner in Node application?

Thanks in advance for your reply.

**Comment by magick93** [comment]
Hi @dsntk 

> you would like to embed a DMN runner in Node application?

Yes, that is exactly it.

**Comment by ghost** [comment]
Hi @magick93!

I like the idea of embedding **dsntk** in Node application. Would you consider helping a little bit with this?

**Comment by ghost** [comment]
Postponed to near future...
