### ISSUE TITLE
`GLIBC_2.32' not found

### ISSUE THREAD

**Issue by DaanJG** [DecisionToolkit/dsntk#7]
Hi!

Thanks for providing dsntk. I really liked dmntk and I am looking forward to using its successor.

However, I get an error when running the dsntk binary I downloaded from github:

```
$ dsntk-0.0.2-linux-ubuntu-x86_64
dsntk-0.0.2-linux-ubuntu-x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by dsntk-0.0.2-linux-ubuntu-x86_64)
dsntk-0.0.2-linux-ubuntu-x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by dsntk-0.0.2-linux-ubuntu-x86_64)
dsntk-0.0.2-linux-ubuntu-x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by dsntk-0.0.2-linux-ubuntu-x86_64)
```

Maybe one solution is to upgrade glibc but I would rather not fearing I might break other things. Another might be to upgrade Ubuntu to 22.04.3, but that's quite a bit of work.

I actually first tried installing through cargo, but that gave me errors for which I'll open a seperate issue.

Here is some info on my OS:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
$ uname -r
5.10.16.3-microsoft-standard-WSL2
```

**Comment by DaanJG** [comment]
I have now managed to install dsntk through cargo. My first attempts failed because rustc was outdated, but I have removed the version from the Ubuntu 20.04 repos and used the recommended method from rust-lang.org to resinstall.

So this is not an issue for me any longer.

**Comment by ghost** [comment]
Hi @DaanJG!

Yes, the version of **dsntk** build for Ubuntu and prepared for download was built using GitHub actions, using `ubuntu-latest` image available from GitHub. So as we expected, it is likely that many users will have the same issues.
We will remove this build from downloadable files for next versions.
But, there is another build named **dsntk-0.0.2-linux-musl-x86_64**, statically compiled, so this should work properly on multiple Linux distributions... Maybe you could try if it works for you.

Of course, the best way to get **dsntk** up and running is to compile it locally using `cargo install` as you did :-)

Thanks for using **Decision Toolkit**!
